pogobot:
    build: ./bot
    environment:
        VIRTUAL_HOST: "pokesock.*"
        PGB_USERNAME: "username"
        PGB_PASSWORD: "password"
        PGB_GOOGLE_API_KEY: "google-api-key"
        PGB_LOCATION: "40.7811648,-73.9720392"
        PGB_RECYCLE_ITEMS: "true"
        PGB_TRANSFER_ON_START: "true"
        PGB_WALK_SPEED: "6"
    volumes:
        - ./data:/usr/local/pogobot/data
ui:
    build: ./ui
    environment:
        VIRTUAL_HOST: "pokeui.*"
        PGBUI_SOCKET_URL: "http://pokesock.localhost"
